### ISSUE TITLE
When language is Arabic seconds don't appear correctly

### ISSUE THREAD

**Issue by ShKhan9** [michaldrabik/classicmaterialtimepicker#10]
Hi, i use this library for changing time , but it doesn't show Arabic numbers correctly may be you need to decrease font size or increase width of the dialog ????

**Comment by developerGM** [comment]
I have the same results.
I have tried to resize font but the hours are cutted.
I think that you need set TextView width autoSize and force lines=1

![image](https://user-images.githubusercontent.com/9252653/112819428-df37f000-9084-11eb-8155-606a2819337f.png)

**Comment by michaldrabik** [comment]
@developerGM I'll be checking this. What are your settings to replicate this? Thanks

**Comment by developerGM** [comment]
Set style as this and I am using a custom font ("gt_america")
```
    <!--    Timepicker style-->
    <style name="CmtpDialogFrameStyle" parent="CmtpDialogTheme">
        <item name="android:windowBackground">@drawable/timepicker_dialog</item>
    </style>

    <style name="CmtpDialogPositiveButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">
        <item name="android:textColor">@color/primary</item>
        <item name="android:textSize">18sp</item>
    </style>

    <style name="CmtpDialogNegativeButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">
        <item name="android:textColor">#A8A8A8</item>
        <item name="android:textSize">18sp</item>
    </style>

    <style name="CmtpViewTheme">
        <item name="cmtpTextFrameDrawable">@drawable/timepicker_text_frame</item>
        <item name="cmtpTextColor">@color/black</item>
        <item name="cmtpTextSize">20sp</item>
    </style>
```

**Comment by michaldrabik** [comment]
@developerGM I've made some modifications which should hopefully help. You can test it out by updating to version 1.1.3

**Comment by developerGM** [comment]
@michaldrabik now it works. Thanks

**Comment by michaldrabik** [comment]
Closing. Feel free to reopen if any more issues occur.
