### ISSUE TITLE
using architecture components along with this libary causes issues in lifecycle

### ISSUE THREAD

**Issue by RodoIndia** [michaldrabik/classicmaterialtimepicker#4]
When we use architecture components with this library, a lifecycle issue arises. ViewModel no longer accepts activity context as a lifecycle owner.

```
chatEvent.outgoingChat.observe(this, Observer {

})
```

The above code doesn't accept context as a lifecycle owner when using this library but when I remove the library, it works perfectly.

**Comment by michaldrabik** [comment]
Hello.
I suppose `this` in above code should be an Activity? Does your activity extends AppCompatActivty?
Can you share your gradle dependencies for Android ViewModel

Regards
