### ISSUE TITLE
BUG :(

### ISSUE THREAD

**Issue by ghost** [michaldrabik/classicmaterialtimepicker#7]
Hey sir, look at this bug when I show the dialog in top of another
![Capture d’écran 2020-10-25 à 15 15 03](https://user-images.githubusercontent.com/54495807/97108249-ee310580-16d4-11eb-86b6-fea3bf3bab79.png)

**Comment by michaldrabik** [comment]
Hi thanks for reporting. Does this happen always or only when you try to open multiple dialogs?

**Comment by ghost** [comment]
Hey, Inside a fragment when I open a DialogFragment and then yours I got that, not tried anything else..

**Comment by frantasmrz** [comment]
Hello, I found solution, add: android:singleLine="true" and android:ellipsize="none" to TextView with id="cmtpTimeNumberValue" inside library in cmtp_value_view.xml file, like this:


```
<TextView
	android:id="@+id/cmtpTimeNumberValue"
	android:layout_width="wrap_content"
	android:layout_height="wrap_content"
	android:layout_marginLeft="20dp"
	android:layout_marginTop="8dp"
	android:layout_marginRight="20dp"
	android:layout_marginBottom="8dp"
	android:singleLine="true"
	android:ellipsize="none"
	android:textColor="?cmtpTextColor"
	android:textSize="?cmtpTextSize"
	android:theme="@style/CmtpViewTheme"
	tools:text="04"
	/>

```
Hope it helps.

**Comment by michaldrabik** [comment]
@frantasmrz @dadou181295 Thanks! I will try to update as soon as possible. 

@frantasmrz Were you able to reproduce the bug and confirm that this solves the issue?

**Comment by frantasmrz** [comment]
@michaldrabik Yes. I was able to reproduce the bug on my real device "Redmi T8" and on emulator device "Pixel 3", and yes this solve the problem for me.

**Comment by michaldrabik** [comment]
Added an released
