### ISSUE TITLE
When we set initial date with calendar object it create an Exception (Bug)

### ISSUE THREAD

**Issue by malikbilal1997** [michaldrabik/classicmaterialtimepicker#8]
`        
        Date date = new Date();

        Calendar calendar = Calendar.getInstance();

        calendar.setTime(date);

       cmtpDateDialogFragment.setInitialDate(calendar);
`

 `java.lang.IllegalStateException: Invalid month. Must be between 1 and 12`

**Comment by michaldrabik** [comment]
@malikbilal1997 Thanks, I'll check this when I get a chance.

**Comment by malikbilal1997** [comment]
> @malikbilal1997 Thanks, I'll check this when I get a chance.

_Sure for work around i'm setting date manually._

`
        Calendar calendar = Calendar.getInstance();

        calendar.setTime(new Date());

        int day = calendar.get(Calendar.DAY_OF_MONTH);

        int month = calendar.get(Calendar.MONTH) + 1;

        int year = calendar.get(Calendar.YEAR);

        cmtpDateDialogFragment.setInitialDate(day, month, year);
`

**Comment by michaldrabik** [comment]
Fixed and released in version 1.1.2 which is now available to use.
